version: '3'
services:
  weather_bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
        - TOKEN_TELEGRAM=${TOKEN_TEL}
        - TOKEN_API_WEATH=${TOKEN_API}
